version: '3'
services:
  # Clash
  clash:
    image: dreamacro/clash:v1.10.6
    container_name: clash
    volumes:
      - ./config/config.yaml:/root/.config/clash/config.yaml
    ports:
      - "7890:7890"
      - "7891:7891"
      - "9090:9090"
    restart: unless-stopped
    networks:
      - default


  # Clash Dashboard
  clash-dashboard:
    image: haishanh/yacd
    container_name: clash-dashboard
    ports:
      - "6789:80"
    restart: unless-stopped
    networks:
      - default

  # Clash auto refresh
  clash-auto-refresh:
    image: yangholmes/refresh-clash-config
    container_name: refresh-clash-config
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/bin/docker:/usr/bin/docker:ro
      - ./config:/work/cmd/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped


# Networks
networks:
  default:
    driver: bridge
    name: clash-bridge
